/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

// Type aliases for backwards compatibility
export type ChatRequest = components["schemas"]["QueryRequest"]
export type ChatResponse = components["schemas"]["QueryResponse"]
export type ChatMessage = {
  id: string
  content: string
  role: 'user' | 'assistant' | 'system'
  timestamp: Date
}

// System Status type
export type SystemStatus = {
  status: string
  timestamp: string
  services: Record<string, unknown>
}

// Graph Data types
export type GraphData = {
  nodes: Array<{
    id: string
    label: string
    type: string
    properties: Record<string, unknown>
  }>
  edges: Array<{
    id: string
    source: string
    target: string
    label: string
    weight: number
  }>
} 